mysite/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('medications/', views.medications, name='medications'),
    path('medications/<int:pk>/', views.MedicationDetailView.as_view(), name='medication'),
    path('medications/<int:pk>/edit/', views.MedicationUpdateView.as_view(), name='edit_medication'),
    path('medications/<int:pk>/delete/', views.MedicationDeleteView.as_view(), name='delete_medication'),
    path('medications/add/', views.add_medication, name='add_medication'),
    path('diseases/', views.diseases, name='diseases'),
    path('diseases/<int:pk>/', views.DiseaseDetailView.as_view(), name='disease'),
    path('diseases/<int:pk>/edit/', views.DiseaseUpdateView.as_view(), name='edit_disease'),
    path('diseases/<int:pk>/delete/', views.DiseaseDeleteView.as_view(), name='delete_disease'),
    path('diseases/add/', views.add_disease, name='add_disease'),
    path('symptoms/', views.symptoms, name='symptoms'),
    path('symptoms/<int:pk>/', views.SymptomDetailView.as_view(), name='symptom'),
    path('symptoms/<int:pk>/edit/', views.SymptomUpdateView.as_view(), name='edit_symptom'),
    path('symptoms/<int:pk>/delete/', views.SymptomDeleteView.as_view(), name='delete_symptom'),
    path('symptoms/add/', views.add_symptom, name='add_symptom'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/main/models.py
from django.db import models


class Diseases(models.Model):
    disease_id = models.AutoField(primary_key=True)
    disease_name = models.CharField(unique=True, max_length=255, blank=False, null=False)
    disease_description = models.TextField(blank=False, null=False)

    def __str__(self):
        return self.disease_name

    def get_absolute_url(self):
        return f'/diseases/{self.disease_id}'

    class Meta:
        verbose_name = 'Болезнь'
        verbose_name_plural = 'Болезни'
        managed = False
        db_table = 'diseases'


class Symptoms(models.Model):
    symptom_id = models.AutoField(primary_key=True)
    symptom_name = models.CharField(unique=True, max_length=255, blank=False, null=False)

    def __str__(self):
        return self.symptom_name

    def get_absolute_url(self):
        return f'/symptoms/{self.symptom_id}'

    class Meta:
        verbose_name = 'Симптом'
        verbose_name_plural = 'Симптомы'
        managed = False
        db_table = 'symptoms'


class DiseaseSymptomLink(models.Model):
    disease = models.OneToOneField('Diseases', on_delete=models.CASCADE, primary_key=True)
    symptom = models.ForeignKey('Symptoms', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.disease} | {self.symptom}"

    class Meta:
        verbose_name = 'Связь болезни и симптома'
        verbose_name_plural = 'Связи болезней и симптомов'
        managed = False
        db_table = 'disease_symptom_link'
        unique_together = (('disease', 'symptom'),)


class Medications(models.Model):
    medication_id = models.AutoField(primary_key=True)
    medication_name = models.CharField(max_length=255, blank=False, null=False)
    expiration_date = models.DateField(blank=False, null=False)
    medication_description = models.TextField(blank=False, null=False)

    def __str__(self):
        return self.medication_name

    def get_absolute_url(self):
        return f'/medications/{self.medication_id}'

    class Meta:
        verbose_name = 'Лекарство'
        verbose_name_plural = 'Лекарства'
        managed = False
        db_table = 'medications'


class MedicationDiseaseLink(models.Model):
    medication = models.OneToOneField('Medications', on_delete=models.CASCADE, primary_key=True)
    disease = models.ForeignKey('Diseases', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.medication} | {self.disease}"

    class Meta:
        verbose_name = 'Связь лекарства и болезни'
        verbose_name_plural = 'Связь лекарства и болезней'
        managed = False
        db_table = 'medication_disease_link'
        unique_together = (('medication', 'disease'),)

mysite/main/forms.py
from django.forms import ModelForm, TextInput, NumberInput, Textarea, DateInput
from .models import *
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(
        max_length=100, required=False,
        label='', widget=TextInput(attrs={'placeholder': 'Название',
                                          'class': 'search-input'})
    )
    date_range = forms.CharField(
        max_length=23, required=False,
        label='', widget=forms.TextInput(attrs={'placeholder': 'Дата DD/MM/YYYY - DD/MM/YYYY',
                                                'class': 'search-input'})
    )


class MedicationForm(ModelForm):
    class Meta:
        model = Medications
        fields = ['medication_name', 'medication_description', 'expiration_date']
        widgets = {
            'medication_name': TextInput(attrs={
                'placeholder': 'Название'
            }),
            'medication_description': Textarea(attrs={
                'placeholder': 'Описание'
            }),
            'expiration_date': DateInput(attrs={
                'placeholder': 'Срок годности',
                'format': '%Y-%m-%d'
            })
        }


class DiseaseForm(ModelForm):
    class Meta:
        model = Diseases
        fields = ['disease_name', 'disease_description']
        widgets = {
            'disease_name': TextInput(attrs={
                'placeholder': 'Название'
            }),
            'disease_description': Textarea(attrs={
                'placeholder': 'Описание'
            })
        }


class SymptomForm(ModelForm):
    class Meta:
        model = Symptoms
        fields = ['symptom_name']
        widgets = {
            'symptom_name': TextInput(attrs={
                'placeholder': 'Название'
            })
        }

mysite/main/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, UpdateView, DeleteView
from .forms import *
from datetime import datetime


class MedicationDetailView(DetailView):
    model = Medications
    template_name = 'main/medication.html'
    context_object_name = 'medication'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        medication_id = self.kwargs.get('pk')
        disease_links = MedicationDiseaseLink.objects.filter(medication__medication_id=medication_id)
        dis = [link.disease for link in disease_links]
        context['diseases'] = dis
        return context


class MedicationUpdateView(UpdateView):
    model = Medications
    template_name = 'main/edit_medication.html'
    form_class = MedicationForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class MedicationDeleteView(DeleteView):
    model = Medications
    template_name = 'main/delete_medication.html'
    title = 'Удалить лекарство'
    context_object_name = 'medication'
    success_url = '/medications/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context

    def delete(self, request, *args, **kwargs):
        medication = self.get_object()
        MedicationDiseaseLink.objects.filter(medication=medication).delete()
        return super().delete(request, *args, **kwargs)


class DiseaseDetailView(DetailView):
    model = Diseases
    template_name = 'main/disease.html'
    context_object_name = 'disease'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        disease_id = self.kwargs.get('pk')
        medication_links = MedicationDiseaseLink.objects.filter(disease__disease_id=disease_id)
        med = set(link.medication.medication_name for link in medication_links)
        symptom_links = DiseaseSymptomLink.objects.filter(disease__disease_id=disease_id)
        sym = [link.symptom for link in symptom_links]
        context['medications'] = med
        context['symptoms'] = sym
        return context


class DiseaseUpdateView(UpdateView):
    model = Diseases
    template_name = 'main/edit_disease.html'
    form_class = DiseaseForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class DiseaseDeleteView(DeleteView):
    model = Diseases
    template_name = 'main/delete_disease.html'
    context_object_name = 'disease'
    success_url = '/diseases/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def delete(self, request, *args, **kwargs):
        disease = self.get_object()
        DiseaseSymptomLink.objects.filter(disease=disease).delete()
        MedicationDiseaseLink.objects.filter(disease=disease).delete()
        return super().delete(request, *args, **kwargs)


class SymptomDetailView(DetailView):
    model = Symptoms
    template_name = 'main/symptom.html'
    context_object_name = 'symptom'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        symptom_id = self.kwargs.get('pk')
        disease_links = DiseaseSymptomLink.objects.filter(symptom__symptom_id=symptom_id)
        dis = [link.disease for link in disease_links]
        context['diseases'] = dis
        return context


class SymptomUpdateView(UpdateView):
    model = Symptoms
    template_name = 'main/edit_symptom.html'
    form_class = SymptomForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class SymptomDeleteView(DeleteView):
    model = Symptoms
    template_name = 'main/delete_symptom.html'
    context_object_name = 'symptom'
    success_url = '/symptoms/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def delete(self, request, *args, **kwargs):
        symptom = self.get_object()
        DiseaseSymptomLink.objects.filter(symptom=symptom).delete()
        return super().delete(request, *args, **kwargs)


def index(request):
    return render(request, 'main/index.html')


def medications(request):
    med = list(enumerate(Medications.objects.all()))
    form = SearchForm(request.GET)
    table_title = 'Количество записей: ' + str(len(med))
    data = {
        'medications': med,
        'form': form,
        'table_title': table_title
    }
    if request.GET and form.is_valid():
        search = form.cleaned_data['search']
        date_range = form.cleaned_data['date_range']
        if search or date_range:
            medications_filtered = Medications.objects.all()
            data['table_title'] = 'По запросу'
            if search:
                medications_filtered = medications_filtered.filter(medication_name__istartswith=search)
                data['table_title'] += " \"" + search + "\" "
            if date_range:
                start_date_str, end_date_str = date_range.split(' - ')
                start_date = datetime.strptime(start_date_str, '%d.%m.%Y').date()
                end_date = datetime.strptime(end_date_str, '%d.%m.%Y').date()
                medications_filtered = medications_filtered.filter(expiration_date__range=[start_date, end_date])
                data['table_title'] += " от " + start_date_str + ' - ' + end_date_str + " "
            data['table_title'] += 'записей найдено: ' + str(len(medications_filtered))
            data['medications'] = list(enumerate(medications_filtered, start=1))
    return render(request, 'main/medications.html', data)


def add_medication(request):
    error = ''
    if request.method == 'POST':
        form = MedicationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('medications')
        else:
            error = 'Форма была заполнена неверно!'
    else:
        form = MedicationForm()
    data = {
        'error': error,
        'form': form
    }
    return render(request, 'main/add_medication.html', data)


def diseases(request):
    dis = list(enumerate(Diseases.objects.all(), start=1))
    form = SearchForm(request.GET)
    table_title = 'Количество записей: ' + str(len(dis))
    data = {
        'diseases': dis,
        'form': form,
        'table_title': table_title
    }
    if form.is_valid() and form.cleaned_data['search']:
        search = form.cleaned_data['search']
        searched = list(enumerate(Diseases.objects.filter(disease_name__istartswith=search), start=1))
        data['diseases'] = searched
        data['table_title'] = 'По запросу "' + search + '" записей найдено: ' + str(len(searched))
    return render(request, 'main/diseases.html', data)


def add_disease(request):
    error = ''
    if request.method == 'POST':
        form = DiseaseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('diseases')
        else:
            error = 'форма была заполнена неверно'
    else:
        form = DiseaseForm()
    data = {
        'error': error,
        'form': form
    }
    return render(request, 'main/add_disease.html', data)


def symptoms(request):
    sym = list(enumerate(Symptoms.objects.all(), start=1))
    form = SearchForm(request.GET)
    table_title = 'Количество записей: ' + str(len(sym))
    data = {
        'symptoms': sym,
        'form': form,
        'table_title': table_title
    }
    if form.is_valid() and form.cleaned_data['search']:
        search = form.cleaned_data['search']
        searched = list(enumerate(Symptoms.objects.filter(symptom_name__istartswith=search), start=1))
        data['symptoms'] = searched
        data['table_title'] = 'По запросу "' + search + '" записей найдено: ' + str(len(searched))
    return render(request, 'main/symptoms.html', data)


def add_symptom(request):
    error = ''
    if request.method == 'POST':
        form = SymptomForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('symptoms')
        else:
            error = 'Форма была заполнена неверна'
    else:
        form = SymptomForm()
    data = {
        'error': error,
        'form': form
    }
    return render(request, 'main/add_symptom.html', data)

mysite/main/templates/main/add_medication.html
{% extends 'main/layout.html' %}
{% block content %}
    <form method="post" action="{% url 'add_medication' %}">
        {% csrf_token %}
        <div class="centered-content">{{ form.medication_name|escape }}</div>
        <div class="centered-content">{{ form.medication_description|escape }}</div>
        <div class="centered-content">{{ form.expiration_date|escape }}</div>
        <span class="centered-content">{{ form.error }}</span>
        <div class="centered-content">
            <button type="submit" class="common-button accept-button">Сохранить запись</button>
        </div>
    </form>
    <script>
        const dateRangeInput = document.querySelector('#id_expiration_date');
        dateRangeInput.addEventListener('input', handleDateInput);
        function handleDateInput(event) {
            const value = event.target.value;
            if (value.length === 2 || value.length === 5) {
                event.target.value = value + '.';
            }
        }
    </script>
{% endblock %}

mysite/main/templates/main/add_symptom.html
{% extends 'main/layout.html' %}
{% block content %}
    <form class="form-group" method="post" action="{% url 'add_symptom' %}">
        {% csrf_token %}
        <div class="centered-content">{{ form.symptom_name|escape }}</div>
        <span class="centered-content">{{ error }}</span>
        <div class="centered-content">
            <button type="submit" class="common-button accept-button">Сохранить запись</button>
        </div>
    </form>
{% endblock %}

mysite/main/templates/main/delete_disease.html
{% extends 'main/layout.html' %}
{% block content %}
    <div class="content-container">
        <p></p>
        <h2> Вы уверены, что хотите удалить запись о болезни "{{disease.disease_name}}"?</h2>
    </div>
    <form method="post" action="{% url 'delete_disease' pk=disease.disease_id %}">
                {% csrf_token %}
                <button type="submit" class="common-button accept-button">Подтвердить</button>
    </form>
    <script>
        function confirmDelete() {
            if (confirm('Вы точно хотите удалить запись об этой болезни?')) {
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '{% url "delete_disease" pk=disease.pk %}', true);
                xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
                xhr.onload = function() {
                    if (xhr.status >= 200 && xhr.status < 400) {
                        var response = JSON.parse(xhr.responseText);
                        alert(response.message);
                        window.location.href = '{% url "diseases" %}';
                    } else {
                        alert('Произошла ошибка при удалении болезни.');
                    }
                };
                xhr.onerror = function() {
                    alert('Произошла ошибка при удалении болезни.');
                };
                xhr.send();
            }
        }
    </script>
{% endblock %}

mysite/main/templates/main/delete_medication.html
{% extends 'main/layout.html' %}
{% block content %}
    <div class="content-container">
        <h2> Вы уверены, что хотите удалить запись о лекарстве "{{ medication.medication_name }}"?</h2>
    </div>
    <form method="post" action="{% url 'delete_medication' pk=medication.medication_id %}">
            {% csrf_token %}
            <button type="submit" class="common-button">Подтвердить</button>
    </form>
{% endblock %}

mysite/main/templates/main/delete_symptom.html
{% extends 'main/layout.html' %}
{% block content %}
    <div class="content-container">
        <p></p>
        <h2> Вы уверены, что хотите удалить запись о симптоме "{{symptom.symptom_name}}"?</h2>
    </div>
    <form method="post" action="{% url 'delete_symptom' pk=symptom.symptom_id %}">
                {% csrf_token %}
                <button type="submit" class="common-button accept-button">Подтвердить</button>
    </form>
    <script>
        function confirmDelete() {
            if (confirm('Вы точно хотите удалить запись об этом симптоме?')) {
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '{% url "delete_symptom" pk=symptom.pk %}', true);
                xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
                xhr.onload = function() {
                    if (xhr.status >= 200 && xhr.status < 400) {
                        var response = JSON.parse(xhr.responseText);
                        alert(response.message);
                        window.location.href = '{% url "symptoms" %}';
                    } else {
                        alert('Произошла ошибка при удалении симптома.');
                    }
                };
                xhr.onerror = function() {
                    alert('Произошла ошибка при удалении симптома.');
                };
                xhr.send();
            }
        }
    </script>
{% endblock %}

mysite/main/templates/main/disease.html
{% extends 'main/layout.html' %}
{% block content %}
    <div class="page-content-container">
        <div class="centered-content">
            <h1>Информация о болезни</h1>
        </div>
        <h2>Название</h2>
        <div class="description">{{ disease.disease_name }}</div>
        <h2>Описание</h2>
        <div class="description">{{ disease.disease_description }}</div>
        <h2>Сопутствующие симптомы</h2>
        <div class="description">
            <ul>
                {% for symptom in symptoms %}
                    <li><a class="name" href="{% url 'symptom' symptom.symptom_id %}">{{ symptom.symptom_name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <h2>Лекарства от этой болезни</h2>
        <div class="description">
            <ul>
                {% for medication in medications %}
                    <li>{{ medication }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="centered-content">
            <a href="{% url 'edit_disease' disease.disease_id %}" class="common-button change-button">Изменить</a>
            <a href="{% url 'delete_disease' disease.disease_id %}" class="common-button delete-button">Удалить</a>
        </div>
    </div>
{% endblock %}

mysite/main/templates/main/edit_disease.html
{% extends 'main/layout.html' %}
{% block content %}
    <form method="post" action="{% url 'edit_disease' pk=object.pk %}">
        {% csrf_token %}
        <div class="centered-content">{{ form.disease_name|escape }}</div>
        <div class="centered-content">{{ form.disease_description|escape }}</div>
        <span class="centered-content">{{ error }}</span>
        <div class="centered-content">
            <button type="submit" class="common-button accept-button">Сохранить изменения</button>
        </div>
    </form>
{% endblock %}

mysite/main/templates/main/edit_medication.html
{% extends 'main/layout.html' %}
{% block content %}
    <form method="post" action="{% url 'edit_medication' pk=object.pk %}">
        {% csrf_token %}
        <div class="centered-content">{{ form.medication_name|escape }}</div>
        <div class="centered-content">{{ form.medication_description|escape }}</div>
        <div class="centered-content">{{ form.expiration_date|escape }}</div>
        <span class="centered-content">{{ form.error }}</span>
        <div class="centered-content">
            <button type="submit" class="common-button accept-button">Сохранить изменения</button>
        </div>
    </form>
    <script>
        const dateRangeInput = document.querySelector('#id_expiration_date');
        dateRangeInput.addEventListener('input', handleDateInput);
        function handleDateInput(event) {
            const value = event.target.value;
            if (value.length === 2 || value.length === 5) {
                event.target.value = value + '.';
            }
        }
    </script>
{% endblock %}

mysite/main/templates/main/index.html
{% extends 'main/layout.html' %}
{% block content %}
    <div class="page-content-container">
        <div class="centered-content">
            <h1>Добро пожаловать в приложение "Домашняя аптечка"</h1>
        </div>
        <div class="description">
            Здесь можете ознакомиться с медицинской базой данных, а также подобрать необходимые лекарства
            в зависимости от потребностей.
        </div>
    </div>
{% endblock %}

mysite/main/templates/main/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyPharmacy</title>
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <header>
        <h1>Домашняя аптечка</h1>
    </header>
    <nav class="main-menu">
        <ul>
            <li><a class="{% if request.path == '/' %}active{% endif %}" href="{% url 'home' %}">Главная</a></li>
            <li><a class="{% if request.path == '/medications/' %}active{% endif %}" href="{% url 'medications' %}">Лекарства</a></li>
            <li><a class="{% if request.path == '/diseases/' %}active{% endif %}" href="{% url 'diseases' %}">Болезни</a></li>
            <li><a class="{% if request.path == '/symptoms/' %}active{% endif %}" href="{% url 'symptoms' %}">Симптомы</a></li>
        </ul>
    </nav>
    {% block content%}
    {% endblock %}
</body>
</html>

mysite/main/templates/main/medication.html
{% extends 'main/layout.html' %}
{% block content %}
    <div class="page-content-container">
        <div class="centered-content">
            <h1>Информация о лекарстве</h1>
        </div>
        <h2>Название</h2>
        <div class="description">{{ medication.medication_name }}</div>
        <h2>Описание</h2>
        <div class="description">{{ medication.medication_description }}</div>
        <h2>Применяется для лечения следующих болезней</h2>
        <div class="description">
            <ul>
                {% for disease in diseases %}
                <li><a class="name" href="{% url 'disease' disease.disease_id %}">{{ disease.disease_name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <h2>Срок годности</h2>
        <div class="description">{{ medication.expiration_date }}</div>
        <div class="centered-content">
            <a href="{% url 'edit_medication' medication.medication_id %}" class="common-button change-button">Изменить</a>
            <a href="{% url 'delete_medication' medication.medication_id %}" class="common-button delete-button">Удалить</a>
        </div>
    </div>
{% endblock %}

mysite/main/templates/main/medications.html
{% extends 'main/layout.html' %}
{% block content %}
    <div class="page-content-container">
        <div class="centered-content">
            <h1>Фильтры</h1>
        </div>
        <form method="get" onsubmit="event.preventDefault(); submitForm();">
            <div class="centered-content">{{ form.search }}</div>
            <div class="centered-content">{{ form.date_range }}</div>
            <div class="centered-content">
                <button type="submit" class="common-button search-button">Найти</button>
            </div>
        </form>
    </div>
    <div class="page-content-container">
        <h1 class="statistic_information">{{ table_title }}</h1>
        <a href="{% url 'add_medication' %}" class="common-button add-button">Добавить</a>
        <table border="1">
            <thead>
                <tr>
                    <th>№</th>
                    <th>ID</th>
                    <th>Название лекарства</th>
                    <th>Срок годности</th>
                </tr>
            </thead>
            <tbody>
                {% for index, medication in medications %}
                    <tr>
                        <td>{{ index }}</td>
                        <td>{{ medication.medication_id }}</td>
                        <td><a class="name" href="{% url 'medication' medication.medication_id %}">{{ medication.medication_name }}</a></td>
                        <td>{{ medication.expiration_date|date:"F d, Y" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        function submitForm() {
            document.querySelector('form').submit();
        }
        const dateRangeInput = document.querySelector('#id_date_range');
        dateRangeInput.addEventListener('input', handleDateInput);
        function handleDateInput(event) {
            const value = event.target.value;
            if (value.length === 2 || value.length === 5 || value.length === 15 || value.length === 18) {
                event.target.value = value + '.';
            } else if (value.length === 10) {
                event.target.value = value + ' - ';
            }
        }
    </script>
{% endblock %}

mysite/main/templates/main/symptom.html
{% extends 'main/layout.html' %}
{% block content %}
    <div class="page-content-container">
        <div class="centered-content">
            <h1>Информация о симптоме</h1>
        </div>
        <h2>Название</h2>
        <div class="description">{{ symptom.symptom_name }}</div>
        <h2>Болезни, имеющие этот симптом</h2>
        <div class="description">
            <ul>
                {% for disease in diseases %}
                    <li><a class="name" href="{% url 'disease' disease.disease_id %}">{{ disease.disease_name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="centered-content">
            <a href="{% url 'edit_symptom' symptom.symptom_id %}" class="common-button change-button">Изменить</a>
            <a href="{% url 'delete_symptom' symptom.symptom_id %}" class="common-button delete-button">Удалить</a>
        </div>
    </div>
{% endblock %}

mysite/main/templates/main/symptoms.html
{% extends 'main/layout.html' %}
{% block content %}
    <div class="page-content-container">
        <div class="centered-content">
            <h1>Фильтры</h1>
        </div>
        <form method="get" onsubmit="event.preventDefault(); submitForm();">
            <div class="centered-content">{{ form.search }}</div>
            <div class="centered-content">
                <button type="submit" class="common-button search-button">Найти</button>
            </div>
        </form>
    </div>
    <div class="page-content-container">
        <h1 class="statistic_information">{{ table_title }}</h1>
        <a href="{% url 'add_symptom' %}" class="common-button add-button">Добавить</a>
        <table border="1">
            <thead>
                <tr>
                    <th>№</th>
                    <th>ID</th>
                    <th>Название симптома</th>
                </tr>
            </thead>
            <tbody>
                {% for index, symptom in symptoms %}
                    <tr>
                        <td class="td-ds">{{ index }}</td>
                        <td class="td-ds">{{ symptom.symptom_id }}</td>
                        <td class="td-ds"><a class="name" href="{% url 'symptom' symptom.symptom_id %}">{{ symptom.symptom_name }}</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        function submitForm() {
            document.querySelector('form').submit();
        }
    </script>
{% endblock %}